apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: devops-platform
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: devops-platform
spec:
  ports:
  - port: 8002
    targetPort: 8002
  selector:
    app: vault-service
---
apiVersion: v1
kind: Service
metadata:
  name: github-service
  namespace: devops-platform
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: github-service
